### ISSUE TITLE
Server 

### ISSUE THREAD

**Issue by isabellaaston** [halvipan/SuperAwesomeKanbanBoard#6]
- [x] requires
- [x] set up db 
- [x] set up all the routes
- [x] get projects: '/' return all projects
- [x] get tasks: '/projectId/tasks' return all tasks
- [x] get users: '/users'
- [x] get users assigned to task: '/projectId/taskId/users' return all users assigned to task
- [x] post edit, delete, add, projects, tasks, users
- [x] listen

**Comment by halvipan** [comment]
instead of separate .get routes from project tasks and users, combined for rendering the project page
